# Generated by Django 3.1.6 on 2022-09-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernmae',
            new_name='username',
        ),
    ]
